// Code generated by "stringer -type=StateRemote -output=zzz_state_remote_string.go"; DO NOT EDIT.

package ranje

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateUnknown-0]
	_ = x[StateFetching-1]
	_ = x[StateFetched-2]
	_ = x[StateFetchFailed-3]
	_ = x[StateReady-4]
	_ = x[StateTaken-5]
}

const _StateRemote_name = "StateUnknownStateFetchingStateFetchedStateFetchFailedStateReadyStateTaken"

var _StateRemote_index = [...]uint8{0, 12, 25, 37, 53, 63, 73}

func (i StateRemote) String() string {
	if i >= StateRemote(len(_StateRemote_index)-1) {
		return "StateRemote(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StateRemote_name[_StateRemote_index[i]:_StateRemote_index[i+1]]
}
