// Code generated by "stringer -type=state"; DO NOT EDIT.

package move

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Init-0]
	_ = x[Failed-1]
	_ = x[Complete-2]
	_ = x[Take-3]
	_ = x[Give-4]
	_ = x[Untake-5]
	_ = x[FetchWait-6]
	_ = x[Serve-7]
	_ = x[Drop-8]
}

const _state_name = "InitFailedCompleteTakeGiveUntakeFetchWaitServeDrop"

var _state_index = [...]uint8{0, 4, 10, 18, 22, 26, 32, 41, 46, 50}

func (i state) String() string {
	if i >= state(len(_state_index)-1) {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
