// Code generated by "stringer -type=PlacementState -output=zzz_placement_state.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PsUnknown-0]
	_ = x[PsPending-1]
	_ = x[PsInactive-2]
	_ = x[PsActive-3]
	_ = x[PsGiveUp-4]
	_ = x[PsDropped-5]
}

const _PlacementState_name = "PsUnknownPsPendingPsInactivePsActivePsGiveUpPsDropped"

var _PlacementState_index = [...]uint8{0, 9, 18, 28, 36, 44, 53}

func (i PlacementState) String() string {
	if i >= PlacementState(len(_PlacementState_index)-1) {
		return "PlacementState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlacementState_name[_PlacementState_index[i]:_PlacementState_index[i+1]]
}
