// Code generated by "stringer -type=Action -output=zzz_action_string.go"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoAction-0]
	_ = x[Prepare-1]
	_ = x[Serve-2]
	_ = x[Deactivate-3]
	_ = x[Drop-4]
}

const _Action_name = "NoActionPrepareServeDeactivateDrop"

var _Action_index = [...]uint8{0, 8, 15, 20, 30, 34}

func (i Action) String() string {
	if i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
