// Code generated by "stringer -type=State"; DO NOT EDIT.

package fsm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pending-0]
	_ = x[Ready-1]
	_ = x[Splitting-2]
	_ = x[Joining-3]
	_ = x[Obsolete-4]
}

const _State_name = "PendingReadySplittingJoiningObsolete"

var _State_index = [...]uint8{0, 7, 12, 21, 28, 36}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
