// Code generated by "stringer -type=RemoteState -output=remote_state_string.go"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NsUnknown-0]
	_ = x[NsPreparing-1]
	_ = x[NsPrepared-2]
	_ = x[NsReadying-3]
	_ = x[NsReady-4]
	_ = x[NsTaking-5]
	_ = x[NsTaken-6]
	_ = x[NsDropping-7]
	_ = x[NsNotFound-8]
}

const _RemoteState_name = "NsUnknownNsPreparingNsPreparedNsReadyingNsReadyNsTakingNsTakenNsDroppingNsNotFound"

var _RemoteState_index = [...]uint8{0, 9, 20, 30, 40, 47, 55, 62, 72, 82}

func (i RemoteState) String() string {
	if i >= RemoteState(len(_RemoteState_index)-1) {
		return "RemoteState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RemoteState_name[_RemoteState_index[i]:_RemoteState_index[i+1]]
}
