// Code generated by "stringer -type=RemoteState -output=remote_state_string.go"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NsUnknown-0]
	_ = x[NsPreparing-1]
	_ = x[NsPreparingError-2]
	_ = x[NsPrepared-3]
	_ = x[NsReadying-4]
	_ = x[NsReadyingError-5]
	_ = x[NsReady-6]
	_ = x[NsTaking-7]
	_ = x[NsTaken-8]
	_ = x[NsDropping-9]
	_ = x[NsDroppingError-10]
	_ = x[NsNotFound-11]
}

const _RemoteState_name = "NsUnknownNsPreparingNsPreparingErrorNsPreparedNsReadyingNsReadyingErrorNsReadyNsTakingNsTakenNsDroppingNsDroppingErrorNsNotFound"

var _RemoteState_index = [...]uint8{0, 9, 20, 36, 46, 56, 71, 78, 86, 93, 103, 118, 128}

func (i RemoteState) String() string {
	if i >= RemoteState(len(_RemoteState_index)-1) {
		return "RemoteState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RemoteState_name[_RemoteState_index[i]:_RemoteState_index[i+1]]
}
