// Code generated by "stringer -type=RemoteState -output=remote_state_string.go"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NsUnknown-0]
	_ = x[NsInactive-1]
	_ = x[NsActive-2]
	_ = x[NsLoading-3]
	_ = x[NsActivating-4]
	_ = x[NsDeactivating-5]
	_ = x[NsDropping-6]
	_ = x[NsNotFound-7]
}

const _RemoteState_name = "NsUnknownNsInactiveNsActiveNsLoadingNsActivatingNsDeactivatingNsDroppingNsNotFound"

var _RemoteState_index = [...]uint8{0, 9, 19, 27, 36, 48, 62, 72, 82}

func (i RemoteState) String() string {
	if i >= RemoteState(len(_RemoteState_index)-1) {
		return "RemoteState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RemoteState_name[_RemoteState_index[i]:_RemoteState_index[i+1]]
}
